# -*- coding: utf-8 -*-
"""intro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aXzlEjGU75UwtXrBjlrmv7mFxoq9XOox

3.7 3.9
3.8 3.10 
are the versions of python
"""

print ("Hello World")

print(id(a))

a = 100
b = 99 + 1
print(a is b)
print(a == b)
print(id(a))
print(id(b))

a = 5
print(a)
print(type(a))
'''Type tells us the type of the variable <class 'int'>'''
print(id(a))
'''id keyword tells us the memory location of the variable'''
a = 6;
print(id(a))
'''Here the value which was assigned to the a will be called as anorphaned object'''



b = 'a'
print(b)
print(type(b))
print(id(b))

a = 101;
b = 'Hello World','Python'
#'Hello' "Hello" ""Hellow"" """Hello""" these all be considered same
print(b)
print(id(a))
print(id(b))

# hardcode Input
a = 5;
b = 6;
print(a,b)

a = int(input('Enter first number: '))
b = int(input('Enter second number: '))
# python by default takes input as an string until you give it proper data type
print(a + b)

a = 5
b = 4
print(a,b)
a,b = 7,8

print(a,b)

"""Python is a **dynamically typed language** """

import this

a = 9 / 2 #Float
print(a)
b = 21 // 2 #Integer
print(b)

a = (int)(input("Enter first number: "))
b = (int)(input("Enter second number: "))
if a>b:
      print(a, 'is greater ')
else:
    print(b, ' is greater ')

"""Practical One"""

y = (int)(input("Enter first number: "))
if y%4 == 0 and y%100 != 0 or y%400 == 0:
  print("Leap Year")
else:
  print("Not a leap year")

"""Practical Two"""

a = (int)(input("Enter first number: "))
b = (int)(input("Enter second number: "))
print("Before ",a,b)
temp = a;
a = b;
b = temp;

print("After",a,b)

a = (int)(input("Enter first number: "))
b = (int)(input("Enter second number: "))
print("Before ",a,b)
a,b = b,a

print("After",a,b)

import os
  
shutdown = input("Do you wish to shutdown your computer ? (yes / no): ")
  
if shutdown == 'no':
    exit()
else:
    os.system("shutdown /s /t 1")